version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
      - "9092:9092" # Puerto de acceso para SonarScanner
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=smartoshdev
      - SONARQUBE_JDBC_PASSWORD=devteam
    networks:
      - sonarnet
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=smartoshdev
      - POSTGRES_PASSWORD=devteam
    networks:
      - sonarnet
    volumes:
      - postgresql:/var/lib/postgresql

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
